### ISSUE TITLE
Provide a working end2end configuration

### ISSUE THREAD

**Issue by cambierr** [wasilak/elastauth#7]
Hi,

I've been looking at this for a few hours and find the idea very interesting but I'm unable to figure out how to get and end2end flow working (at least with my use-case which is based on nginx).

Would you mind sharing your configuration, event traefik based, to ease re-use ?

Thank you :-)

**Comment by wasilak** [comment]
I'll give it a try and add a docker-compose based example folder to project 👍

**Comment by wasilak** [comment]
Sorry it took so much time, but I was able to come up with an example proposal: https://github.com/wasilak/elastauth/tree/example/example

There are surely some descriptions missing, but it is a start, I did not wanted to keep you waiting longer ;)
